spring:
  profiles:
    #运行的环境
    active: test
  application:
    name: IMServer
  datasource:
    url: jdbc:mysql://${IMServer.mysql.ip}:${IMServer.mysql.port}/${IMServer.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${IMServer.mysql.username}
    password: ${IMServer.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # Redis服务器地址
    host: ${IMServer.redis.host}
    # Redis服务器端口号
    port: ${IMServer.redis.port}
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
#    password: ${IMServer.redis.password}
  jackson:
    serialization:
      write-dates-as-timestamps: true
# 微信相关配置
wx:
  mp:
    #    callback: http://f4cd-113-92-129-127.ngrok.io
    callback: ${IMServer.wx.callback}
    configs:
      - appId: ${IMServer.wx.appId} # 第一个公众号的appid
        secret: ${IMServer.wx.secret} # 公众号的appsecret
        token: ${IMServer.wx.token} # 接口配置里的Token值
        aesKey: ${IMServer.wx.aesKey} # 接口配置里的EncodingAESKey值
# JWT相关配置
jwt:
  secret: ${mallchat.jwt.secret}